version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - sam build
      - export BUCKET=du-codepipeline-artifact
      - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
